name: CMake Build and Docker Run

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v1

      - name: Configure CMake
        run: cmake -H. -B_build -DCMAKE_INSTALL_PREFIX=_install

      - name: Build project
        run: cmake --build _build

      - name: Install project
        run: cmake --build _build --target install

      - name: Build Docker image
        run: docker build -t logger .

      - name: Prepare logs directory
        run: mkdir -p logs

      - name: Run Docker container with input
        run: |
          echo -e "text1\ntext2\ntext3\n" | docker run -i -v ${{ github.workspace }}/logs:/home/logs logger

      - name: Show log file contents
        run: cat logs/log.txt

      - name: Upload logs artifact
        uses: actions/upload-artifact@v4
        with:
          name: logs
          path: logs/log.txt

